type: object
properties:
  abort_incomplete_multipart_uploads_after:
    type: integer
    format: int64
    description: Duration of time after which incomplete multipart uploads will be
      aborted. Measured in milliseconds. Must be a multiple of 86400000 to represent
      a whole number of days.
    example: 86400000
  keep_current_version_for:
    type: integer
    format: int64
    description: Time after which current versions will be marked expired. Measured
      in milliseconds. Must be a multiple of 86400000 to represent a whole number
      of days.
    example: 86400000
  keep_current_version_until:
    type: integer
    format: int64
    description: Time after which current versions will be marked expired. Measured
      in milliseconds, time since epoch. Must be a valid date, accurate to day.
    example: 1636588800000
