description: Global settings for administrative accounts.
type: object
properties:
  lockout_duration:
    description: The lockout duration, in milliseconds, if a user is locked out after
      reaching the maximum number of login attempts. Ranges from 1 second to 90 days.
    type: integer
    format: int64
    minimum: 1000
    maximum: 7776000000
    example: 3600000
  max_login_attempts:
    description: Maximum number of failed login attempts allowed before the user is
      locked out.
    type: integer
    format: int32
    minimum: 1
    maximum: 20
    example: 10
  min_password_length:
    description: Minimum password length. If not specified, defaults to 1.
    type: integer
    format: int32
    example: 1
  single_sign_on_enabled:
    description: If `true`, then single sign-on is enabled for the array.
    type: boolean
    example: true
