type: object
description: The configuration of eradication feature.
properties:
  disabled_delay:
    description: The eradication delay in milliseconds for destroyed objects that
      cannot be manually eradicated. Destroyed objects that cannot be manually eradicated
      will be automatically eradicated after the configured delay time passes. Valid
      values are `86400000` and any multiple of `86400000` in the range of `86400000`
      and `2592000000`. Any other values are rounded down to the nearest multiple
      of `86400000`.
    type: integer
    format: int64
    example: 86400000
  eradication_delay:
    description: Eradication delay in milliseconds for all destroyed objects. Automatically
      eradicate destroyed objects after the configured delay time passes. Updating
      this field will update both `eradication_disabled_delay` and `eradication_enabled_delay`
      if both `eradication_disabled_delay` and `eradication_enabled_delay` have the
      same value. If `eradication_disabled_delay` and `eradication_enabled_delay`
      have different values, trying to configure `eradication_delay` will result in
      an error. This field has been deprecated and will be removed in a future REST
      version. Valid values are `86400000` and any multiple of `86400000` in the range
      of `86400000` and `2592000000`. Any other values are rounded down to the nearest
      multiple of `86400000`.
    type: integer
    format: int64
    example: 86400000
  enabled_delay:
    description: The eradication delay in milliseconds for destroyed objects that
      can be manually eradicated. Destroyed objects that can be manually eradicated
      will be automatically eradicated after the configured delay time passes. Valid
      values are `86400000` and any multiple of `86400000` in the range of `86400000`
      and `2592000000`. Any other values are rounded down to the nearest multiple
      of `86400000`.
    type: integer
    format: int64
    example: 86400000
  manual_eradication:
    description: Manual eradication status applied on the array level. If status is
      `all-disabled`, you cannot eradicate objects, files, and directories. If at
      least one local object has `manual_eradication` disabled, then the status will
      be `partially-disabled`. Values include `all-disabled`, `partially-disabled`,
      and `all-enabled`.
    type: string
    readOnly: true
    example: all-disabled
