consumes:
- application/json
definitions:
  Admin:
    $ref: ../models/FB1.2/admin.yaml
  Alert:
    $ref: ../models/FB1.2/alert.yaml
  AlertWatcher:
    $ref: ../models/FB1.2/alert-watcher.yaml
  AlertWatcherTest:
    $ref: ../models/FB1.2/alert-watcher-test.yaml
  ArrayHttpSpecificPerformance:
    $ref: ../models/FB1.2/array-http-specific-performance.yaml
  ArrayPerformance:
    $ref: ../models/FB1.2/array-performance.yaml
  ArrayS3SpecificPerformance:
    $ref: ../models/FB1.2/array-s3-specific-performance.yaml
  ArraySpace:
    $ref: ../models/FB1.2/array-space.yaml
  Blade:
    $ref: ../models/FB1.2/blade.yaml
  Certificate:
    $ref: ../models/FB1.2/certificate.yaml
  Dns:
    $ref: ../models/FB1.2/dns.yaml
  FileSystem:
    $ref: ../models/FB1.2/file-system.yaml
  FileSystemSnapshot:
    $ref: ../models/FB1.1/file-system-snapshot.yaml
  Hardware:
    $ref: ../models/FB1.2/hardware.yaml
info:
  description: "## Pure Swagger UI for FlashBlade\nA light weight tool to explore\
    \ the API for FlashBlade, community supported.  \nFor help with this tool, use\
    \ [Pure1 Community](https://community.purestorage.com/) or the [code-purestorage\
    \ Slack](https://community.purestorage.com/discussion/9561/join-the-new-pure-code-slack-team-for-api-and-extensibility-discussions)\n\
    \n## Authentication\nUse an api-token (header param) to start a session at /api/login,\
    \ that returns an x-auth-token header which expires in 30 minutes by default.\
    \ This is\ndifferent than FlashArray, which uses a cookie instead.  The x-auth-token\
    \ is saved and added by the built in proxy server.\n\nUse \"pureadmin create --api-token\"\
    \ on the CLI to create an API Token.  Or use \"pureadmin list --api-token --expose\"\
    \ to show a token already created.  Note, it only shows tokens for user that is\
    \ logged in.\n\n## Proxy\nThis Swagger tool includes a proxy server that forwards\
    \ API calls to the array.  In the Swagger UI, you will \\\nsee curl API calls\
    \ to IP 127.0.0.1, that is the proxy server. To see the API call details view\
    \ the console output.\n\n## Error Codes\nUse HTTP Response codes to determine\
    \ command results.  Error message json formats are different depending on the\
    \ endpoint.\n\n## Official Documention\nGo to the Pure support portal for the\
    \ [full documentation](https://support.purestorage.com/FlashBlade/Purity_FB/Purity%2F%2F%2F%2FFB_REST_API/Management_REST_API/Management_REST_API_Reference_Guides)."
  title: FlashBlade REST API Client
  version: 1.2
paths:
  /api/1.2/admins:
    $ref: ../paths/FB1.2/admins.path.yaml
  /api/1.2/alert-watchers:
    $ref: ../paths/FB1.2/alert-watchers.path.yaml
  /api/1.2/alert-watchers/test:
    $ref: ../paths/FB1.2/alert-watchers-test.path.yaml
  /api/1.2/alerts:
    $ref: ../paths/FB1.2/alerts.path.yaml
  /api/1.2/arrays/http-specific-performance:
    $ref: ../paths/FB1.2/arrays-http-specific-performance.path.yaml
  /api/1.2/arrays/performance:
    $ref: ../paths/FB1.2/arrays-performance.path.yaml
  /api/1.2/arrays/s3-specific-performance:
    $ref: ../paths/FB1.2/arrays-s3-specific-performance.path.yaml
  /api/1.2/arrays/space:
    $ref: ../paths/FB1.2/arrays-space.path.yaml
  /api/1.2/blades:
    $ref: ../paths/FB1.2/blades.path.yaml
  /api/1.2/certificates:
    $ref: ../paths/FB1.2/certificates.path.yaml
  /api/1.2/dns:
    $ref: ../paths/FB1.2/dns.path.yaml
  /api/1.2/file-system-snapshots:
    $ref: ../paths/FB1.1/file-system-snapshots.path.yaml
  /api/1.2/file-systems:
    $ref: ../paths/FB1.2/file-systems.path.yaml
  /api/1.2/hardware:
    $ref: ../paths/FB1.2/hardware.path.yaml
  /api/api_version:
    $ref: ../paths/FB1.0/api_version.path.yaml
  /api/login:
    post:
      description: Create a new session with API_KEY
      parameters:
      - in: header
        name: api-token
        required: true
        type: string
      responses:
        200:
          description: User logged in
          headers:
            x-auth-token:
              description: authentication token, pass this back for future API Calls.
              type: string
          schema:
            example:
              username: pureuser
            properties:
              username:
                description: The user name logged in.
                type: string
            type: object
      tags:
      - Authorization
  /api/logout:
    $ref: ../paths/FB1.0/logout.path.yaml
  /oauth2_pub_priv_key_pair:
    get:
      description: "Returns a public and private key pair, This is not part of the\
        \ FlashArray API, \nit's a helper endpoint making it easier to generate an\
        \ oauth2 token_id in this Swagger UI. \nThey keys are generated in the Docker\
        \ container running on this machine.\n\nRecommend to NOT use this API but\
        \ to use OpenSSL instead for production use cases:\n  You can generate a public\
        \ and private RSA key pair like this:\n\n    openssl genrsa -des3 -out private.pem\
        \ 2048\n    \n    That generates a 2048-bit RSA key pair, encrypts them with\
        \ a password you provide and writes them to a file. \n    You need to next\
        \ extract the public key file. You will use this, for instance, on your web\
        \ server to encrypt \n    content so that it can only be read with the private\
        \ key.\n    \n    Export the RSA Public Key to a File\n    This is a command\
        \ that is\n    \n    openssl rsa -in private.pem -outform PEM -pubout -out\
        \ public.pem"
      responses:
        200:
          description: Token Generated
          schema:
            properties:
              private_key:
                description: Private key in PEM format.
                type: string
              public_key:
                description: Public key in PEM format.
                type: string
            type: object
      tags:
      - Auth Helpers
  /oauth2_token_from_private_key:
    post:
      consumes:
      - text/plain
      description: "Authenticates to Flasharray, This returns a token_id (think session\
        \ id), from an existing API Client, \nThis is not part of the FlashArray API,\
        \ it's a helper endpoint making it easy to generate an \noauth2 token_id in\
        \ this Swagger UI.  The private key is being passed into the Docker container\
        \ in\norder to sign the JWT token.  Take a look at the Docker container output\
        \ to see more details \nof what is happening.\n\nCopy the output value, Authorization\
        \ header, and then click on the green Authorize button at the \ntop of the\
        \ page.  Paste in the value into "
      parameters:
      - description: Issuer value displayed in the FlashArray API Registration page
          or pureapiclient list ) by default it's the same name as API Client
        in: header
        name: issuer_name
        type: string
      - description: Client Id value displayed in the FlashArray API Registration
          page or pureapiclient list
        in: header
        name: client_id
        type: string
      - description: Key Id value displayed in the FlashArray API Registration page
          or pureapiclient list
        in: header
        name: key_id
        type: string
      - description: The name of a valid user on the FlashArray that will be authenticated
          to.
        in: header
        name: username
        type: string
      - description: Private key in PEM format that was used to create the Public
          key for this API Client specified as the issuer in this call.
        in: body
        name: private_key
        required: true
        schema:
          type: string
      produces:
      - application/json
      responses:
        200:
          description: Token Generated
          schema:
            example:
              username: pureuser
            properties:
              Authorization:
                description: An OAuth bearer token to be used in the Authorization
                  header for authorization to API endpoints.
                type: string
              description:
                desciption: How to use token
                type: string
            type: object
      tags:
      - Auth Helpers
produces:
- application/json
schemes:
- http
- https
security:
- AuthorizationHeader: []
securityDefinitions:
  ApiToken:
    in: header
    name: api-token
    type: apiKey
  AuthorizationHeader:
    in: header
    name: x-auth-token
    type: apiKey
swagger: '2.0'
tags:
- description: A set of endpoints not in the Purity API, but to make OAuth using this
    tool simple and easy to understand.
  name: Auth Helpers
- name: Authorization
- name: Administrators
- name: Alerts
- name: Alert Watchers
- name: Arrays
- name: Blades
- name: Certificates
- name: DNS
- name: File Systems
- name: File System Snapshots
- name: Hardware
