basePath: /
consumes:
- application/json
definitions:
  Admin:
    $ref: ../models/FB1.8/admin.yaml
  AdminCache:
    $ref: ../models/FB1.8/admin-cache.yaml
  Alert:
    $ref: ../models/FB1.8/alert.yaml
  AlertWatcher:
    $ref: ../models/FB1.9/alert-watcher.yaml
  AlertWatcherTest:
    $ref: ../models/FB1.9/alert-watcher-test.yaml
  Array:
    $ref: ../models/FB1.9/array.yaml
  ArrayConnection:
    $ref: ../models/FB1.9/array-connection.yaml
  ArrayConnectionKey:
    $ref: ../models/FB1.9/array-connection-key.yaml
  ArrayConnectionPath:
    $ref: ../models/FB1.9/array-connection-path.yaml
  ArrayHttpSpecificPerformance:
    $ref: ../models/FB1.2/array-http-specific-performance.yaml
  ArrayNfsSpecificPerformance:
    $ref: ../models/FB1.9/array-nfs-specific-performance.yaml
  ArrayPerformance:
    $ref: ../models/FB1.3/array-performance.yaml
  ArrayS3SpecificPerformance:
    $ref: ../models/FB1.2/array-s3-specific-performance.yaml
  ArraySpace:
    $ref: ../models/FB1.2/array-space.yaml
  Audit:
    $ref: ../models/FB1.9/audit.yaml
  Blade:
    $ref: ../models/FB1.8/blade.yaml
  Bucket:
    $ref: ../models/FB1.9/bucket.yaml
  BucketPerformance:
    $ref: ../models/FB1.8/bucket-performance.yaml
  BucketReplicaLink:
    $ref: ../models/FB1.9/bucket-replica-link.yaml
  BucketS3SpecificPerformance:
    $ref: ../models/FB1.8/bucket-s3-specific-performance.yaml
  Certificate:
    $ref: ../models/FB1.8/certificate.yaml
  CertificateGroup:
    $ref: ../models/FB1.8/certificate-group.yaml
  CertificateGroupUse:
    $ref: ../models/FB1.9/certificate-group-use.yaml
  CertificateUse:
    $ref: ../models/FB1.9/certificate-use.yaml
  ClientPerformance:
    $ref: ../models/FB1.4/client-performance.yaml
  DNS:
    $ref: ../models/FB1.2/dns.yaml
  DirectoryService:
    $ref: ../models/FB1.9/directory-service.yaml
  DirectoryServiceRole:
    $ref: ../models/FB1.8/directory-service-role.yaml
  FileSystem:
    $ref: ../models/FB1.9/file-system.yaml
  FileSystemPerformance:
    $ref: ../models/FB1.5/file-system-performance.yaml
  FileSystemReplicaLink:
    $ref: ../models/FB1.9/file-system-replica-link.yaml
  FileSystemSnapshot:
    $ref: ../models/FB1.9/file-system-snapshot.yaml
  FileSystemSnapshotTransfer:
    $ref: ../models/FB1.9/file-system-snapshot-transfer.yaml
  GroupQuota:
    $ref: ../models/FB1.8/group-quota.yaml
  Hardware:
    $ref: ../models/FB1.8/hardware.yaml
  HardwareConnector:
    $ref: ../models/FB1.8/hardware-connector.yaml
  Keytab:
    $ref: ../models/FB1.9/keytab.yaml
  KeytabFileBase64:
    $ref: ../models/FB1.9/keytab-file-base64.yaml
  KeytabFileBinary:
    $ref: ../models/FB1.9/keytab-file-binary.yaml
  LinkAggregationGroup:
    $ref: ../models/FB1.8/link-aggregation-group.yaml
  Member:
    $ref: ../models/FB1.8/member.yaml
  NetworkInterface:
    $ref: ../models/FB1.9/network-interface.yaml
  ObjectStoreAccessKey:
    $ref: ../models/FB1.8/object-store-access-key.yaml
  ObjectStoreAccount:
    $ref: ../models/FB1.8/object-store-account.yaml
  ObjectStoreRemoteCredentials:
    $ref: ../models/FB1.9/object-store-remote-credentials.yaml
  ObjectStoreUser:
    $ref: ../models/FB1.8/object-store-user.yaml
  Policy:
    $ref: ../models/FB1.9/policy.yaml
  PolicyFileSystem:
    $ref: ../models/FB1.8/policy-member.yaml
  PolicyFileSystemSnapshot:
    $ref: ../models/FB1.9/policy-file-system-snapshot.yaml
  PolicyMember:
    $ref: ../models/FB1.9/policy-member-with-remote.yaml
  QuotaSetting:
    $ref: ../models/FB1.8/quota-setting.yaml
  RelationshipPerformanceReplication:
    $ref: ../models/FB1.9/relationship-performance-replication.yaml
  ResourcePerformanceReplication:
    $ref: ../models/FB1.9/resource-performance-replication.yaml
  SMTP:
    $ref: ../models/FB1.3/smtp.yaml
  SNMPAgent:
    $ref: ../models/FB1.9/snmp-agent.yaml
  SNMPManager:
    $ref: ../models/FB1.9/snmp-manager.yaml
  SNMPManagerTest:
    $ref: ../models/FB1.9/snmp-manager-test.yaml
  Subnet:
    $ref: ../models/FB1.9/subnet.yaml
  Support:
    $ref: ../models/FB1.6/support.yaml
  Target:
    $ref: ../models/FB1.9/target.yaml
  TestResult:
    $ref: ../models/FB1.3/test-result.yaml
  UserQuota:
    $ref: ../models/FB1.8/user-quota.yaml
info:
  description: "## Pure Swagger UI for FlashBlade\nA light weight tool to explore\
    \ the API for FlashBlade, community supported.  \nFor help with this tool, use\
    \ [Pure1 Community](https://community.purestorage.com/) or the [code-purestorage\
    \ Slack](https://community.purestorage.com/discussion/9561/join-the-new-pure-code-slack-team-for-api-and-extensibility-discussions)\n\
    \n## Authentication\nUse an api-token (header param) to start a session at /api/login,\
    \ that returns an x-auth-token header which expires in 30 minutes by default.\
    \ This is\ndifferent than FlashArray, which uses a cookie instead.  The x-auth-token\
    \ is saved and added by the built in proxy server.\n\nUse \"pureadmin create --api-token\"\
    \ on the CLI to create an API Token.  Or use \"pureadmin list --api-token --expose\"\
    \ to show a token already created.  Note, it only shows tokens for user that is\
    \ logged in.\n\n## Proxy\nThis Swagger tool includes a proxy server that forwards\
    \ API calls to the array.  In the Swagger UI, you will \\\nsee curl API calls\
    \ to IP 127.0.0.1, that is the proxy server. To see the API call details view\
    \ the console output.\n\n## Error Codes\nUse HTTP Response codes to determine\
    \ command results.  Error message json formats are different depending on the\
    \ endpoint.\n\n## Official Documention\nGo to the Pure support portal for the\
    \ [full documentation](https://support.purestorage.com/FlashBlade/Purity_FB/Purity%2F%2F%2F%2FFB_REST_API/Management_REST_API/Management_REST_API_Reference_Guides)."
  title: FlashBlade REST API Client
  version: 1.9
  x-logo:
    url:
      $ref: ../redoc/PS-LogoBase64-FA.txt
paths:
  /api/1.9/admins:
    $ref: ../paths/FB1.8/admins.path.yaml
  /api/1.9/admins/cache:
    $ref: ../paths/FB1.8/admins-cache.path.yaml
  /api/1.9/alert-watchers:
    $ref: ../paths/FB1.9/alert-watchers.path.yaml
  /api/1.9/alert-watchers/test:
    $ref: ../paths/FB1.9/alert-watchers-test.path.yaml
  /api/1.9/alerts:
    $ref: ../paths/FB1.8/alerts.path.yaml
  /api/1.9/array-connections:
    $ref: ../paths/FB1.9/array-connections.path.yaml
  /api/1.9/array-connections/connection-key:
    $ref: ../paths/FB1.9/array-connection-key.path.yaml
  /api/1.9/array-connections/path:
    $ref: ../paths/FB1.9/array-connections-path.path.yaml
  /api/1.9/array-connections/performance/replication:
    $ref: ../paths/FB1.9/array-connections-performance-replication.path.yaml
  /api/1.9/arrays:
    $ref: ../paths/FB1.9/arrays.path.yaml
  /api/1.9/arrays/clients/performance:
    $ref: ../paths/FB1.4/clients-performance.path.yaml
  /api/1.9/arrays/http-specific-performance:
    $ref: ../paths/FB1.2/arrays-http-specific-performance.path.yaml
  /api/1.9/arrays/nfs-specific-performance:
    $ref: ../paths/FB1.9/arrays-nfs-specific-performance.path.yaml
  /api/1.9/arrays/performance:
    $ref: ../paths/FB1.3/arrays-performance.path.yaml
  /api/1.9/arrays/performance/replication:
    $ref: ../paths/FB1.9/arrays-performance-replication.path.yaml
  /api/1.9/arrays/s3-specific-performance:
    $ref: ../paths/FB1.2/arrays-s3-specific-performance.path.yaml
  /api/1.9/arrays/space:
    $ref: ../paths/FB1.9/arrays-space.path.yaml
  /api/1.9/audits:
    $ref: ../paths/FB1.9/audits.path.yaml
  /api/1.9/blades:
    $ref: ../paths/FB1.9/blades.path.yaml
  /api/1.9/bucket-replica-links:
    $ref: ../paths/FB1.9/bucket-replica-links.path.yaml
  /api/1.9/buckets:
    $ref: ../paths/FB1.9/buckets.path.yaml
  /api/1.9/buckets/performance:
    $ref: ../paths/FB1.9/buckets-performance.path.yaml
  /api/1.9/buckets/s3-specific-performance:
    $ref: ../paths/FB1.9/buckets-s3-specific-performance.path.yaml
  /api/1.9/certificate-groups:
    $ref: ../paths/FB1.8/certificate-groups.path.yaml
  /api/1.9/certificate-groups/certificates:
    $ref: ../paths/FB1.8/certificate-groups-certificates.path.yaml
  /api/1.9/certificate-groups/uses:
    $ref: ../paths/FB1.9/certificate-groups-uses.path.yaml
  /api/1.9/certificates:
    $ref: ../paths/FB1.9/certificates.path.yaml
  /api/1.9/certificates/certificate-groups:
    $ref: ../paths/FB1.8/certificates-certificate-groups.path.yaml
  /api/1.9/certificates/uses:
    $ref: ../paths/FB1.9/certificates-uses.path.yaml
  /api/1.9/directory-services:
    $ref: ../paths/FB1.9/directory-services.path.yaml
  /api/1.9/directory-services/roles:
    $ref: ../paths/FB1.8/directory-service-roles.path.yaml
  /api/1.9/directory-services/test:
    $ref: ../paths/FB1.9/directory-service-test.path.yaml
  /api/1.9/dns:
    $ref: ../paths/FB1.2/dns.path.yaml
  /api/1.9/file-system-replica-links:
    $ref: ../paths/FB1.9/file-system-replica-links.path.yaml
  /api/1.9/file-system-replica-links/policies:
    $ref: ../paths/FB1.9/file-system-replica-links-policies.path.yaml
  /api/1.9/file-system-replica-links/transfer:
    $ref: ../paths/FB1.9/file-system-replica-links-transfer.path.yaml
  /api/1.9/file-system-snapshots:
    $ref: ../paths/FB1.9/file-system-snapshots.path.yaml
  /api/1.9/file-system-snapshots/policies:
    $ref: ../paths/FB1.9/file-system-snapshots-policies.path.yaml
  /api/1.9/file-system-snapshots/transfer:
    $ref: ../paths/FB1.9/file-system-snapshots-transfer.path.yaml
  /api/1.9/file-systems:
    $ref: ../paths/FB1.9/file-systems.path.yaml
  /api/1.9/file-systems/performance:
    $ref: ../paths/FB1.9/file-systems-performance.path.yaml
  /api/1.9/file-systems/policies:
    $ref: ../paths/FB1.8/file-systems-policies.path.yaml
  /api/1.9/hardware:
    $ref: ../paths/FB1.8/hardware.path.yaml
  /api/1.9/hardware-connectors:
    $ref: ../paths/FB1.8/hardware-connectors.path.yaml
  /api/1.9/keytabs:
    $ref: ../paths/FB1.9/keytabs.path.yaml
  /api/1.9/keytabs/download:
    $ref: ../paths/FB1.9/keytabs-download.path.yaml
  /api/1.9/keytabs/upload:
    $ref: ../paths/FB1.9/keytabs-upload.path.yaml
  /api/1.9/link-aggregation-groups:
    $ref: ../paths/FB1.8/link-aggregation-groups.path.yaml
  /api/1.9/logs:
    $ref: ../paths/FB1.4/logs.path.yaml
  /api/1.9/network-interfaces:
    $ref: ../paths/FB1.9/network-interfaces.path.yaml
  /api/1.9/object-store-access-keys:
    $ref: ../paths/FB1.8/object-store-access-keys.path.yaml
  /api/1.9/object-store-accounts:
    $ref: ../paths/FB1.8/object-store-accounts.path.yaml
  /api/1.9/object-store-remote-credentials:
    $ref: ../paths/FB1.9/object-store-remote-credentials.path.yaml
  /api/1.9/object-store-users:
    $ref: ../paths/FB1.8/object-store-users.path.yaml
  /api/1.9/policies:
    $ref: ../paths/FB1.9/policies.path.yaml
  /api/1.9/policies/file-system-replica-links:
    $ref: ../paths/FB1.9/policies-file-system-replica-links.path.yaml
  /api/1.9/policies/file-system-snapshots:
    $ref: ../paths/FB1.9/policies-file-system-snapshots.path.yaml
  /api/1.9/policies/file-systems:
    $ref: ../paths/FB1.8/policies-file-systems.path.yaml
  /api/1.9/policies/members:
    $ref: ../paths/FB1.9/policies-members.path.yaml
  /api/1.9/quotas/groups:
    $ref: ../paths/FB1.9/quotas-groups.path.yaml
  /api/1.9/quotas/settings:
    $ref: ../paths/FB1.8/quotas-settings.path.yaml
  /api/1.9/quotas/users:
    $ref: ../paths/FB1.9/quotas-users.path.yaml
  /api/1.9/smtp:
    $ref: ../paths/FB1.3/smtp.path.yaml
  /api/1.9/snmp-agents:
    $ref: ../paths/FB1.9/snmp-agents.path.yaml
  /api/1.9/snmp-agents/mib:
    $ref: ../paths/FB1.9/snmp-agents-mib.path.yaml
  /api/1.9/snmp-managers:
    $ref: ../paths/FB1.9/snmp-managers.path.yaml
  /api/1.9/snmp-managers/test:
    $ref: ../paths/FB1.9/snmp-managers-test.path.yaml
  /api/1.9/subnets:
    $ref: ../paths/FB1.9/subnets.path.yaml
  /api/1.9/support:
    $ref: ../paths/FB1.6/support.path.yaml
  /api/1.9/support/test:
    $ref: ../paths/FB1.6/support-test.path.yaml
  /api/1.9/targets:
    $ref: ../paths/FB1.9/targets.path.yaml
  /api/1.9/targets/performance/replication:
    $ref: ../paths/FB1.9/targets-performance-replication.path.yaml
  /api/1.9/usage/groups:
    $ref: ../paths/FB1.9/usage-groups.path.yaml
  /api/1.9/usage/users:
    $ref: ../paths/FB1.9/usage-users.path.yaml
  /api/api_version:
    $ref: ../paths/FB1.0/api_version.path.yaml
  /api/login:
    $ref: ../paths/FB1.0/login.path.yaml
  /api/logout:
    $ref: ../paths/FB1.0/logout.path.yaml
  /api_version:
    get:
      description: Lists supported API versions on this array.
      responses:
        200:
          description: List supported API versions
      tags:
      - api
  /login:
    post:
      description: Create a new session with API_KEY
      parameters:
      - in: header
        name: api-token
        required: true
        type: string
      responses:
        200:
          description: User logged in
          headers:
            x-auth-token:
              description: authentication token, pass this back for future API Calls.
              type: string
          schema:
            example:
              username: pureuser
            properties:
              username:
                description: The user name logged in.
                type: string
            type: object
      tags:
      - auth
produces:
- application/json
schemes:
- http
- https
security:
- AuthorizationHeader: []
securityDefinitions:
  ApiToken:
    in: header
    name: api-token
    type: apiKey
  AuthorizationHeader:
    in: header
    name: x-auth-token
    type: apiKey
swagger: '2.0'
tags:
- name: api
- name: auth
- description: Authorization endpoint description (placeholder)
  name: Authorization
- description: Administrators endpoint description (placeholder)
  name: Administrators
- description: Alerts endpoint description (placeholder)
  name: Alerts
- description: Alert Watchers endpoint description (placeholder)
  name: Alert Watchers
- description: Arrays endpoint description (placeholder)
  name: Arrays
- description: Array Connections endpoint description (placeholder)
  name: Array Connections
- description: Audits endpoint description (placeholder)
  name: Audits
- description: Blades endpoint description (placeholder)
  name: Blades
- description: Buckets endpoint description (placeholder)
  name: Buckets
- description: Bucket Replica Links endpoint description (placeholder)
  name: Bucket Replica Links
- description: Certificates endpoint description (placeholder)
  name: Certificates
- description: Certificate Groups endpoint description (placeholder)
  name: Certificate Groups
- description: Clients endpoint description (placeholder)
  name: Clients
- description: Directory Services endpoint description (placeholder)
  name: Directory Services
- description: DNS endpoint description (placeholder)
  name: DNS
- description: File Systems endpoint description (placeholder)
  name: File Systems
- description: File System Replica Links endpoint description (placeholder)
  name: File System Replica Links
- description: File System Snapshots endpoint description (placeholder)
  name: File System Snapshots
- description: Hardware endpoint description (placeholder)
  name: Hardware
- description: Hardware Connectors endpoint description (placeholder)
  name: Hardware Connectors
- description: Keytabs endpoint description (placeholder)
  name: Keytabs
- description: Link Aggregation Groups endpoint description (placeholder)
  name: Link Aggregation Groups
- description: Logs endpoint description (placeholder)
  name: Logs
- description: Network Interfaces endpoint description (placeholder)
  name: Network Interfaces
- description: Object Store Access Keys endpoint description (placeholder)
  name: Object Store Access Keys
- description: Object Store Accounts endpoint description (placeholder)
  name: Object Store Accounts
- description: Object Store Remote Credentials endpoint description (placeholder)
  name: Object Store Remote Credentials
- description: Object Store Users endpoint description (placeholder)
  name: Object Store Users
- description: Policies endpoint description (placeholder)
  name: Policies
- description: Quotas endpoint description (placeholder)
  name: Quotas
- description: SMTP endpoint description (placeholder)
  name: SMTP
- description: SNMP Agents endpoint description (placeholder)
  name: SNMP Agents
- description: SNMP Managers endpoint description (placeholder)
  name: SNMP Managers
- description: Subnets endpoint description (placeholder)
  name: Subnets
- description: Support endpoint description (placeholder)
  name: Support
- description: Targets endpoint description (placeholder)
  name: Targets
- description: Usage endpoint description (placeholder)
  name: Usage
