consumes:
- application/json
definitions:
  Alert:
    $ref: ../models/Pure1-1.1/alert.yaml
  Array:
    $ref: ../models/Pure1-1.1/array.yaml
  Audit:
    $ref: ../models/Pure1-1.1/audit.yaml
  Blade:
    $ref: ../models/Pure1-1.1/blade.yaml
  Bucket:
    $ref: ../models/Pure1-1.1/bucket.yaml
  BucketReplicaLink:
    $ref: ../models/Pure1-1.1/bucket-replica-link.yaml
  Controller:
    $ref: ../models/Pure1-1.1/controller.yaml
  Directory:
    $ref: ../models/Pure1-1.1/directory.yaml
  Drive:
    $ref: ../models/Pure1-1.1/drive.yaml
  FileSystem:
    $ref: ../models/Pure1-1.1/file-system.yaml
  FileSystemReplicaLink:
    $ref: ../models/Pure1-1.1/file-system-replica-link.yaml
  FileSystemSnapshot:
    $ref: ../models/Pure1-1.1/file-system-snapshot.yaml
  Hardware:
    $ref: ../models/Pure1-1.1/hardware.yaml
  HardwareConnector:
    $ref: ../models/Pure1-1.1/hardware-connector.yaml
  Metric:
    $ref: ../models/Pure1-1.0/metric.yaml
  MetricHistory:
    $ref: ../models/Pure1-1.1/metric-history.yaml
  NetworkInterface:
    $ref: ../models/Pure1-1.1/network-interface.yaml
  Pod:
    $ref: ../models/Pure1-1.1/pod.yaml
  PodReplicaLink:
    $ref: ../models/Pure1-1.1/pod-replica-link.yaml
  Policy:
    $ref: ../models/Pure1-1.1/policy.yaml
  PolicyMember:
    $ref: ../models/Pure1-1.0/policy-member.yaml
  Port:
    $ref: ../models/Pure1-1.1/port.yaml
  Subscription:
    $ref: ../models/Pure1-1.0/subscription.yaml
  SubscriptionLicense:
    $ref: ../models/Pure1-1.1/subscription-license.yaml
  SupportContract:
    $ref: ../models/Pure1-1.1/support-contract.yaml
  Tag:
    $ref: ../models/Pure1-1.0/tag.yaml
  Target:
    $ref: ../models/Pure1-1.1/target.yaml
  Volume:
    $ref: ../models/Pure1-1.1/volume.yaml
  VolumeSnapshot:
    $ref: ../models/Pure1-1.1/volume-snapshot.yaml
info:
  description: '## Pure Swagger UI for Pure1

    Please visit [Pure1 Swagger](https://static.pure1.purestorage.com/api-swagger/index.html)
    for the official available swagger.

    For help try the [code-purestorage Slack](https://community.purestorage.com/discussion/9561/join-the-new-pure-code-slack-team-for-api-and-extensibility-discussions)


    ## Getting Started Blog

    [https://blog.purestorage.com/introducing-the-pure1-rest-api/](https://blog.purestorage.com/introducing-the-pure1-rest-api/)

    A walkthrough on getting started with the Pure1 API written'
  title: Pure1 Public REST API
  version: '1.1'
  x-logo:
    altText: Pure Storage logo
    backgroundColor: '#fff'
    url:
      $ref: ../redoc/PS-LogoBase64-P1.txt
paths:
  /api/1.1/alerts:
    $ref: ../paths/Pure1-1.1/alerts.path.yaml
  /api/1.1/arrays:
    $ref: ../paths/Pure1-1.1/arrays.path.yaml
  /api/1.1/arrays/support-contracts:
    $ref: ../paths/Pure1-1.1/arrays-support-contracts.path.yaml
  /api/1.1/arrays/tags:
    $ref: ../paths/Pure1-1.0/arrays-tags.path.yaml
  /api/1.1/arrays/tags/batch:
    $ref: ../paths/Pure1-1.0/arrays-tags-batch.path.yaml
  /api/1.1/audits:
    $ref: ../paths/Pure1-1.1/audits.path.yaml
  /api/1.1/blades:
    $ref: ../paths/Pure1-1.1/blades.path.yaml
  /api/1.1/bucket-replica-links:
    $ref: ../paths/Pure1-1.1/bucket-replica-links.path.yaml
  /api/1.1/buckets:
    $ref: ../paths/Pure1-1.1/buckets.path.yaml
  /api/1.1/controllers:
    $ref: ../paths/Pure1-1.1/controllers.path.yaml
  /api/1.1/directories:
    $ref: ../paths/Pure1-1.1/directories.path.yaml
  /api/1.1/drives:
    $ref: ../paths/Pure1-1.1/drives.path.yaml
  /api/1.1/file-system-replica-links:
    $ref: ../paths/Pure1-1.1/file-system-replica-links.path.yaml
  /api/1.1/file-system-replica-links/policies:
    $ref: ../paths/Pure1-1.0/file-system-replica-links-policies.path.yaml
  /api/1.1/file-system-snapshots:
    $ref: ../paths/Pure1-1.1/file-system-snapshots.path.yaml
  /api/1.1/file-system-snapshots/policies:
    $ref: ../paths/Pure1-1.0/file-system-snapshots-policies.path.yaml
  /api/1.1/file-systems:
    $ref: ../paths/Pure1-1.1/file-systems.path.yaml
  /api/1.1/file-systems/policies:
    $ref: ../paths/Pure1-1.0/file-systems-policies.path.yaml
  /api/1.1/hardware:
    $ref: ../paths/Pure1-1.1/hardware.path.yaml
  /api/1.1/hardware-connectors:
    $ref: ../paths/Pure1-1.1/hardware-connectors.path.yaml
  /api/1.1/metrics:
    $ref: ../paths/Pure1-1.0/metrics.path.yaml
  /api/1.1/metrics/history:
    $ref: ../paths/Pure1-1.1/metrics-history.path.yaml
  /api/1.1/network-interfaces:
    $ref: ../paths/Pure1-1.1/network-interfaces.path.yaml
  /api/1.1/object-store-accounts:
    $ref: ../paths/Pure1-1.1/object-store-accounts.path.yaml
  /api/1.1/pod-replica-links:
    $ref: ../paths/Pure1-1.1/pod-replica-links.path.yaml
  /api/1.1/pods:
    $ref: ../paths/Pure1-1.1/pods.path.yaml
  /api/1.1/policies:
    $ref: ../paths/Pure1-1.1/policies.path.yaml
  /api/1.1/policies/file-system-replica-links:
    $ref: ../paths/Pure1-1.0/policies-file-system-replica-links.path.yaml
  /api/1.1/policies/file-system-snapshots:
    $ref: ../paths/Pure1-1.0/policies-file-system-snapshots.path.yaml
  /api/1.1/policies/file-systems:
    $ref: ../paths/Pure1-1.0/policies-file-systems.path.yaml
  /api/1.1/policies/members:
    $ref: ../paths/Pure1-1.0/policies-members.path.yaml
  /api/1.1/ports:
    $ref: ../paths/Pure1-1.1/ports.path.yaml
  /api/1.1/subscription-licenses:
    $ref: ../paths/Pure1-1.1/subscription-licenses.path.yaml
  /api/1.1/subscriptions:
    $ref: ../paths/Pure1-1.0/subscriptions.path.yaml
  /api/1.1/targets:
    $ref: ../paths/Pure1-1.1/targets.path.yaml
  /api/1.1/volume-snapshots:
    $ref: ../paths/Pure1-1.1/volume-snapshots.path.yaml
  /api/1.1/volumes:
    $ref: ../paths/Pure1-1.1/volumes.path.yaml
  /oauth2/1.0/token:
    $ref: ../paths/TEx-v2/oauth-token.path.yaml
produces:
- application/json
schemes:
- https
security:
- AuthorizationHeader: []
securityDefinitions:
  AuthorizationHeader:
    in: header
    name: Authorization
    type: apiKey
swagger: '2.0'
tags:
- description: Handles authorization access to other API endpoints through OAuth 2.0
    Token Exchange.
  name: Authorization
- description: Provides access to capacity, health, and hardware related array alerts.
  name: Alerts
- description: Provides information about FlashArray and FlashBlade appliances.
  name: Arrays
- description: Provides access to CLI audit logs from FlashArray and FlashBlade appliances.
  name: Audits
- description: Provides information about FlashBlade blades.
  name: Blades
- description: Provides information about FlashBlade buckets.
  name: Buckets
- description: Provides information about replica links between buckets.
  name: Bucket Replica Links
- description: Provides information about FlashArray controllers.
  name: Controllers
- description: Provides information about FlashArray directories.
  name: Directories
- description: Provides information about FlashArray drives.
  name: Drives
- description: Provides information about FlashArray and FlashBlade file systems.
  name: File Systems
- description: Provides information about replica links between FlashBlade file systems.
  name: File System Replica Links
- description: Provides information about FlashBlade file system snapshots.
  name: File System Snapshots
- description: Provides information about hardware components.
  name: Hardware
- description: Provides information about FlashBlade hardware connectors.
  name: Hardware Connectors
- description: Provides information about historical metrics for arrays, volumes,
    file systems and pods.
  name: Metrics
- description: Provides information about network interfaces available on arrays.
  name: Network Interfaces
- description: Provides information about object store accounts.
  name: Object Store Accounts
- description: Provides information about FlashArray pods. A pod is the pairing of
    two arrays that replicate some volumes with each other.
  name: Pods
- description: Provides information about replica links between FlashArray pods.
  name: Pod Replica Links
- description: Provides information about FlashBlade policies and the members they
    apply to.
  name: Policies
- description: Provides information about FlashArray ports.
  name: Ports
- description: Provides information about Pure1 subscription offerings.
  name: Subscriptions
- description: Provides information about FlashBlade external replication targets.
  name: Targets
- description: Provides information about block storage volumes on FlashArray arrays.
  name: Volumes
- description: Provides information about snapshots of block storage volumes on FlashArray
    arrays.
  name: Volume Snapshots
