consumes:
- application/json
definitions:
  Array:
    $ref: ../models/Pure1-1.1.b/array.yaml
info:
  description: '## Pure Swagger UI for Pure1

    Please visit [Pure1 Swagger](https://static.pure1.purestorage.com/api-swagger/index.html)
    for the official available swagger.

    For help try the [code-purestorage Slack](https://community.purestorage.com/discussion/9561/join-the-new-pure-code-slack-team-for-api-and-extensibility-discussions)


    ## Getting Started Blog

    [https://blog.purestorage.com/introducing-the-pure1-rest-api/](https://blog.purestorage.com/introducing-the-pure1-rest-api/)

    A walkthrough on getting started with the Pure1 API written'
  title: Pure1 Public REST API
  version: 1.1.b
  x-logo:
    altText: Pure Storage logo
    backgroundColor: '#fff'
    url:
      $ref: ../redoc/PS-LogoBase64-P1.txt
paths:
  /api/1.1.b/arrays:
    $ref: ../paths/Pure1-1.1.b/arrays.path.yaml
produces:
- application/json
schemes:
- https
security:
- AuthorizationHeader: []
securityDefinitions:
  AuthorizationHeader:
    in: header
    name: Authorization
    type: apiKey
swagger: '2.0'
tags:
- description: Provides information about FlashArray and FlashBlade appliances.
  name: Arrays
