get:
  summary: GET syslog-servers/settings (placeholder)
  description: GET syslog-servers/settings (placeholder)
  parameters:
  - $ref: ../../queries/FB1.0/filter.query.yaml
  - $ref: ../../queries/FB1.8/ids.query.yaml
  - $ref: ../../queries/FB1.0/limit.query.yaml
  - $ref: ../../queries/FB1.0/names.query.yaml
  - $ref: ../../queries/FB1.0/sort.query.yaml
  - $ref: ../../queries/FB1.0/start.query.yaml
  - $ref: ../../queries/FB1.0/token.query.yaml
  responses:
    200:
      description: OK
      schema:
        $ref: ../../responses/FB1.10/syslog-server-settings-get-response.yaml
  tags:
  - Syslog
patch:
  summary: PATCH syslog-servers/settings (placeholder)
  description: PATCH syslog-servers/settings (placeholder)
  parameters:
  - name: syslog-server-settings
    in: body
    required: true
    schema:
      $ref: ../../models/FB1.10/syslog-server-settings.yaml
  - $ref: ../../queries/FB1.8/ids.query.yaml
  - $ref: ../../queries/FB1.0/names.query.yaml
  responses:
    200:
      description: OK
      schema:
        $ref: ../../responses/FB1.10/syslog-server-settings-response.yaml
  tags:
  - Syslog
