description: The configuration of eradication feature.
properties:
  eradication_delay:
    description: The eradication delay in milliseconds. Automatically eradicate destroyed
      items after the delay time. Valid values are `86400000` and any multiple of
      `86400000` in the range of `86400000` and `2592000000`. Any other values will
      be rounded down to the nearest multiple of `86400000`.
    example: 86400000
    format: int64
    type: integer
type: object
