description: The status of the eradication functionality
properties:
  manual_eradication:
    description: The manual eradication status of pod. If `all-enabled`, the pod and
      its contents can be eradicated. If `partially-disabled`, the pod cannot be eradicated
      because the pod contains some non-empty protection groups that are retention-locked.
      If `all-disabled`, the pod and its contents cannot be eradicated. Values include
      `all-disabled`, `all-enabled`, and `partially-disabled`.
    example: all-enabled
    readOnly: true
    type: string
type: object
