type: object
description: Configuration settings related to bucket eradication.
properties:
  eradication_delay:
    description: Eradication delay in milliseconds. Automatically eradicate destroyed
      buckets after the configured delay time passes.
    type: integer
    format: int64
    example: 86400000
  manual_eradication:
    description: The manual eradication status of the bucket. If `disabled`, the bucket
      cannot be eradicated after it has been destroyed, unless it is empty. If `enabled`,
      the bucket can be eradicated. Valid values are `disabled` and `enabled`.
    type: string
    example: enabled
