allOf:
- $ref: ../../models/FB2.8/_object-lock-config-base.yaml
- type: object
  properties:
    default_retention:
      description: The retention period, in milliseconds, used to apply locks on new
        objects if none is specified by the S3 client. Valid values are any multiple
        of `86400000` (1 day), up to `3153600000000` (36500 days). If there is no
        default, this value is `null`. Use "" to clear.
      type: string
      example: '86400000'
