type: object
description: The status of the eradication functionality
properties:
  manual_eradication:
    description: The manual eradication status of the container. If `all-enabled`,
      the container and its contents can be eradicated. If `partially-disabled`, the
      container cannot be eradicated because the container contains some non-empty
      protection groups that are retention-locked. If `all-disabled`, the container
      and its contents cannot be eradicated. Values include `all-disabled`, `all-enabled`,
      and `partially-disabled`.
    type: string
    readOnly: true
    example: all-enabled
