allOf:
- type: object
  description: Diagnostics tools
  properties:
    version:
      description: Version of the diagnostics tool.
      type: string
      readOnly: true
      example: 1.0.0
    last_updated:
      description: Date the diagnostics tool was last updated.
      type: integer
      format: int64
      example: 1672531200000
