get:
  summary: GET quotas-settings
  description: List notification attributes of a group or user quota.
  parameters:
  - $ref: ../../queries/FB2.0/ids.query.yaml
  - $ref: ../../queries/FB2.0/names.query.yaml
  responses:
    200:
      description: OK
      schema:
        $ref: ../../responses/FB2.0/quota-setting-get-response.yaml
  tags:
  - Quotas
patch:
  summary: PATCH quotas-settings
  description: Modify the notification attributes of a group or user quota.
  parameters:
  - name: quota-setting
    in: body
    required: true
    schema:
      $ref: ../../models/FB2.0/quota-setting.yaml
  responses:
    200:
      description: OK
      schema:
        $ref: ../../responses/FB2.0/quota-setting-response.yaml
  tags:
  - Quotas
