allOf:
- $ref: ../../models/FB2.8/_bucket-eradication-config.yaml
- properties:
    eradication_mode:
      description: The eradication mode of the bucket. If it's `permission-based`
        the bucket can be eradicated based on user permissions. If it's `retention-based`
        the bucket can never be eradicated as long as there are locked objects still
        being retained. Valid values are `permission-based` and `retention-based`.
      type: string
      example: permission-based
    eradication_delay:
      readOnly: true
      description: Minimum eradication delay in milliseconds. Automatically eradicate
        destroyed buckets after the delay time passes unless automatic eradication
        is delayed due to other configuration values.
      type: integer
      format: int64
      example: 86400000
