get:
  summary: List global admin settings
  description: Return global admin settings.
  parameters:
  - $ref: ../../queries/FB2.14/x-request-id.header.yaml
  - $ref: ../../queries/FB2.0/continuation_token.query.yaml
  - $ref: ../../queries/FB2.0/filter.query.yaml
  - $ref: ../../queries/FB2.0/limit.query.yaml
  - $ref: ../../queries/FB2.0/offset.query.yaml
  - $ref: ../../queries/FB2.0/sort.query.yaml
  responses:
    200:
      description: OK
      headers:
        $ref: ../../responses/FB2.14/headers-all-default.response.yaml
      schema:
        $ref: ../../responses/FB2.3/admin-settings-get-response.yaml
  tags:
  - Administrators
patch:
  summary: Update global admin settings
  description: Update properties for global admin settings.
  parameters:
  - $ref: ../../queries/FB2.14/x-request-id.header.yaml
  - name: admin-setting
    in: body
    required: true
    schema:
      $ref: ../../models/FB2.3/admin-setting.yaml
  responses:
    200:
      description: OK
      headers:
        $ref: ../../responses/FB2.14/headers-all-default.response.yaml
      schema:
        $ref: ../../responses/FB2.3/admin-settings-response.yaml
  tags:
  - Administrators
