name: Release

"on":
  release:
    types:
      - created

jobs:
  release:
    runs-on: ubuntu-latest
    name: Release
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tox

      - name: Build image
        run: |
          tox -e podman -- ${{ github.event.release.tag_name }}

      - name: Debug image storage
        run: |
          echo "Docker Images:"
          docker images
          echo "Podman Images:"
          podman images
          
      - name: Push swagger
        uses: redhat-actions/push-to-registry@v2
        with:
          image: swagger
          tags: ${{ github.event.release.tag_name }} latest
          registry: quay.io/purestorage/
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_TOKEN }}
