name: Release

"on":
  release:
    types:
      - created

jobs:
  release:
    runs-on: ubuntu-latest
    name: Release
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tox

      - name: Login to image registry
        uses: docker/login-action@v1
        with:
          registry: registry.redhat.io
          username: ${{ secrets.RH_REG_ACCT }}
          password: ${{ secrets.RH_REG_TOKEN }}

      - name: Build image
        env:
          DOCKER_BUILDKIT: 1
        run: |
          tox -e podman -- --tag=swagger:${{ github.event.release.tag_name }}
          
      - name: Retag image
        run: |
         podman tag swagger:${{ github.event.release.tag_name }} swagger:latest

      - name: Push swagger
        uses: redhat-actions/push-to-registry@v2.1.1
        with:
          image: swagger
          tags: ${{ github.event.release.tag_name }} latest
          registry: quay.io/purestorage/
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_TOKEN }}
